# This file was generated by GoReleaser. DO NOT EDIT.
cask "jard" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "2466a048065c7587d14404c150e2aa425c52f23a1ff31b09a0ae6931e5f988a3"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2ba2a55eb1e5dbb545dab7eebe9845498f179f48455c1285af73dbf003b094d"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "327b75632241b9c60317121776b98945f234844918ecb98a96efe25147276e1e"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be642975a9f148dabd05ccbc24f8c3243463d83f7f7b2278235ecd496f4d104b"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jard"
  desc "a Nix-based sandbox for running coding agents in isolated containers"
  homepage "https://github.com/rhizomatous/jardiniere"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jard"]
    end
  end

  # No zap stanza required

end
