# This file was generated by GoReleaser. DO NOT EDIT.
cask "jard" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "7581358ad5451dcdf6f6989de1b2cfcaf228003f8a661ce94716e736b029d7d3"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "58597d0df073c80ba52294021a8d4ecbe7a115c239858c32a7716185a1dc2fa3"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "17dce827ba8a50ca89a750482047cebf3dd96721511b94462ee663f2d89f7104"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "86f5a4b582037601d971c80d1cd561b8ba4f474c27dff9fc2923c378bb9fa1f7"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jard"
  desc "a Nix-based sandbox for running coding agents in isolated containers"
  homepage "https://github.com/rhizomatous/jardiniere"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jard"]
    end
  end

  # No zap stanza required

end
