# This file was generated by GoReleaser. DO NOT EDIT.
cask "jard" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "476d0b788d085bb83cf19b2d03a621c20c1568d98064a381d861c9c0a248a57e"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "26edc70f8815a911cbd4294562b2c8826f37301a7fdb9b2bec922298c73d877f"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9d5e7008c8fbf425987e1f8d48c4b61292cc2b5aa0378a3e7621069c15f8cb92"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "925c477fa002103b54a3e7c859d03ca7c87751bcf6fcd90f18ccb5f82349d25f"
      url "https://github.com/rhizomatous/jardiniere/releases/download/v#{version}/jardiniere_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jard"
  desc "a Nix-based sandbox for running coding agents in isolated containers"
  homepage "https://github.com/rhizomatous/jardiniere"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jard"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jard"]
    end
  end

  # No zap stanza required

end
