# This file was generated by GoReleaser. DO NOT EDIT.
cask "plbx" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "cf07079648f1c10a9b890d7bd471f3d7feb71e5ec721053285fded29324dcda8"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "40a3641c8a58a9ed4c80cd9e528f57a604fd4aee8c5305e6f2e14288c3de8787"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3bda8ad0e718ffefc84166035522f76e63018ff299cc384626cdd7064e0c4e0"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d27f2186636fded30c6e7065f41c2ee34be8f326f201742087247073a34ea206"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "plbx"
  desc "a Nix-based sandbox for running coding agents in isolated containers"
  homepage "https://github.com/rhizomatous/planterbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plbx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/plbx"]
    end
  end

  # No zap stanza required

end
