# This file was generated by GoReleaser. DO NOT EDIT.
cask "plbx" do
  version "0.6.2"

  on_macos do
    on_intel do
      sha256 "48247fc0d0b9f8931d128b9427fb47aa27814fc19a008fc5102bf346be202662"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e539558e1b90038a799cc5b4a7897227a1933008fb995aad4935dc968e24a348"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f02f84a05dcbb5debe42d43c6c3bfaded30499ae3768805f46385facc325845a"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "465d2671b8c941550e859221a14fe6050ead07c4c1f26b35aa4d3fbd098bc470"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "plbx"
  desc "a Nix-based sandbox for running coding agents in isolated containers"
  homepage "https://github.com/rhizomatous/planterbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plbx"
  binary "plbxd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
