# This file was generated by GoReleaser. DO NOT EDIT.
cask "plbx" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "f69d2a8ce325f6fadf5d8509e77f9bedc35e4aa9bf18588a003e9ae2deab5300"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ca9d09c4f3e7cbdcbc1b00b3b00224f013cc962c9d616c6f81fac0e5871aec8"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eefcac927610224469f8d3d3a684df7edf266287622e24d1e65c63934153190e"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e958531be8c3492ea69d7de5f1511692cbebc7792bcc59627ff416a7ca8158b"
      url "https://github.com/rhizomatous/planterbox/releases/download/v#{version}/planterbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "plbx"
  desc "a Nix-based sandbox for running coding agents in isolated containers"
  homepage "https://github.com/rhizomatous/planterbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plbx"
  binary "plbxd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
